#define H 32
#define W 32
#define K 16
#define C 16
#define tile_count_h 16
#define tile_count_w 16
#define tile_num_h_per_kernel 8
#define tile_num_w_per_kernel 4
#define k_per_kernel 4
#define c_per_kernel 2
#define tile_height 4
#define tile_width 4
